' ******************************************************************************
' swxJRNL.swj - journal recorded on 04/17/25 by lucho
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = _
Application.SldWorks

Dim myModelView As Object
boolstatus = swApp.LoadFile2("E:\facu\monorepositorio\telecomunicaciones 2 año\Gestion-de-Recursos-Hidricos\C prototipo\Extructura 3D\Archivos editables\cup_holder_fer.STEP", "r")
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
retval = swApp.Callback ( "fworks@FWPlaybackManager", 0, "SetAutomaticFeatureRecognition 0")

retval = swApp.Callback ( "fworks@FWPlaybackManager", 0, "SetInteractiveFeatureRecognition 1")

'FeatureWorks Block ClearSelection
#IF FWORKS_ENABLE_SWAPI_CALLS THEN
boolstatus = Part.FeatureManager.EditRollback(swMoveRollbackBarTo_e.swMoveRollbackBarToPreviousPosition, "")
#END IF
'FeatureWorks Block ForceRebuild
retval = swApp.Callback ( "fworks@FWPlaybackManager", 0, "RecognizeFeatures")
retval = swApp.Callback ( "fworks@FWPlaybackManager", 0, "SetAutoDimOptions 0 0 0 0")
retval = swApp.Callback ( "fworks@FWPlaybackManager", 0, "SetAutoRelOptions 0")
Part.WindowRedraw
Part.ViewDisplayShaded
Part.WindowRedraw
'FeatureWorks Block ForceRebuild
#IF FWORKS_ENABLE_SWAPI_CALLS THEN
#END IF
'FeatureWorks Block ForceRebuild
Part.WindowRedraw
boolstatus = Part.ForceRebuild3(True)
'FeatureWorks Block ForceRebuild
#IF FWORKS_ENABLE_SWAPI_CALLS THEN
#END IF
'FeatureWorks Block ForceRebuild
Part.ViewDisplayShaded
Part.WindowRedraw
Part.ViewDisplayShaded
'FeatureWorks Block Commenting From This Line
#IF FWORKS_ENABLE_SWAPI_CALLS THEN
Part.ViewDisplayShaded
Part.WindowRedraw
Part.ViewDisplayShaded
boolstatus = Part.EditRebuild3()
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.012497784432686369, 0, 7.2262591121078277, False, 0, Nothing, 0)
Dim myFeature As Object
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.020999999999999908, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.027009536897661984, 0, 7.2262591121078277, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.037009536897661975, 0.017320508075688783, 7.2262591121078277, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.042009536897661952, -0.0086602540378443917, 7.2262591121078277, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.037009536897661947, -0.017320508075688783, 7.2262591121078277, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.03200953689766195, -0.00866025403784439, 7.2262591121078277, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.04200953689766198, 0.0086602540378443917, 7.2262591121078277, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.032009536897661985, 0.00866025403784439, 7.2262591121078277, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.047009536897661991, 0, 7.2262591121078277, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.027997268448830739, -0.025984691182163015, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.012997268448830672, -0.034644945220007287, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.027997268448830596, -0.043305199257851819, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.022997268448830672, -0.034644945220007384, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.017997268448830751, -0.025984691182162945, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.017997268448830584, -0.043305199257851722, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.0079972684488305839, -0.043305199257851631, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.03299726844883067, -0.034644945220007446, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.037997268448830744, -0.025984691182163098, 7.2262591121078277, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.017997268448831111, 0.025984691182162744, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.03299726844883117, 0.034644945220007065, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.02799726844883112, 0.025984691182162692, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.027997268448831204, 0.043305199257851486, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.022997268448831158, 0.03464494522000712, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.012997268448831138, 0.034644945220007127, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.0079972684488311737, 0.043305199257851541, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.017997268448831174, 0.043305199257851493, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.037997268448831133, 0.025984691182162643, 7.2262591121078277, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.ViewDisplayWireframe
Part.ViewDisplayShaded
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.037009536897661982, 0, 7.2252591121078273, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0.001000000000000334, 0, False, False, False, False, 0, 0, False, False, True, True, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
Part.WindowRedraw
Part.ViewDisplayShaded
Part.ViewDisplayShaded
#END IF
'FeatureWorks Block Commenting Up To This Line
boolstatus = Part.ForceRebuild3(True)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.03085749017515127, 0.05145692664825674, 7.1446936585849699, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Cortar-Extruir1", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Cortar-Extruir28", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Cortar-Extruir26", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Cortar-Extruir23", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0048296812390472774, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.011239087857817003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.056195439289085013
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0096593624780945547, -0.078673615004719019
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.078673615004719019
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.044956351431268013
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.089912702862536026
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.033717263573451006
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.019318724956189109, -0.15734723000943804
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.024148406195236387, -0.16858631786725503
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.043467131151425496, -0.24725993287197406
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.048296812390472774, -0.26973810858760805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.062785856107614599, -0.32593354787669304
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.13040139345427648, -0.51699804145958217
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.10142330601999282, -0.3596508114501441
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.062785856107614599, -0.26973810858760805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.096593624780945547, -0.25849902072979108
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.048296812390472774, -0.12362996643598703
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.024148406195236387, -0.067434527146902012
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0096593624780945547, -0.044956351431268013
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0048296812390472774, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0048296812390472774, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.011239087857817003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.022478175715634006
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.096593624780945547, 0.067434527146902012
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.043467131151425496, 0.033717263573451006
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.20284661203998564, 0.11239087857817003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.10142330601999282, 0.067434527146902012
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.043467131151425496, 0.044956351431268013
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.028978087434283664, 0.056195439289085013
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.019318724956189109, 0.022478175715634006
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.028978087434283664, 0.067434527146902012
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.019318724956189109, 0.011239087857817003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.019318724956189109, 0.067434527146902012
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0048296812390472774, 0.022478175715634006, 0.001567719275666235, 0.053977238316633702, 7.2186160985888819
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0048296812390472774, 0.044956351431268013, 0.001567719275666235, 0.053977238316633702, 7.2186160985888819
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.019318724956189109, 0.078673615004719019, 0.001567719275666235, 0.053977238316633702, 7.2186160985888819
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024148406195236387, 0.14610814215162105, 0.001567719275666235, 0.053977238316633702, 7.2186160985888819
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.019318724956189109, 0.12362996643598703, 0.001567719275666235, 0.053977238316633702, 7.2186160985888819
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014489043717141832, 0.033717263573451006, 0.001567719275666235, 0.053977238316633702, 7.2186160985888819
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.011239087857817003, 0.001567719275666235, 0.053977238316633702, 7.2186160985888819
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.011239087857817003, 0.001567719275666235, 0.053977238316633702, 7.2186160985888819
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.011239087857817003, 0.001567719275666235, 0.053977238316633702, 7.2186160985888819
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0096593624780945547, 0.022478175715634006, 0.001567719275666235, 0.053977238316633702, 7.2186160985888819
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.022478175715634006, 0.001567719275666235, 0.053977238316633702, 7.2186160985888819
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.033807768673330942, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.019318724956189109, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0096593624780945547, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024148406195236387, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.019318724956189109, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.033807768673330942, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024148406195236387, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014489043717141832, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0096593624780945547, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0048296812390472774, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.019318724956189109, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014489043717141832, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0096593624780945547, 0, -0.011095209357250724, 0.047208079398387781, 7.2252591121080627
boolstatus = Part.Extension.SelectByID2("Sólido importado4", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Sólido importado4", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
retval = swApp.Callback ( "fworks@FWPlaybackManager", 0, "SetAutomaticFeatureRecognition 0")

retval = swApp.Callback ( "fworks@FWPlaybackManager", 0, "SetInteractiveFeatureRecognition 1")

'FeatureWorks Block ClearSelection
#IF FWORKS_ENABLE_SWAPI_CALLS THEN
Part.ClearSelection2 True
boolstatus = Part.FeatureManager.EditRollback(swMoveRollbackBarTo_e.swMoveRollbackBarToPreviousPosition, "")
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
#END IF
'FeatureWorks Block ForceRebuild
retval = swApp.Callback ( "fworks@FWPlaybackManager", 0, "RecognizeFeatures")
retval = swApp.Callback ( "fworks@FWPlaybackManager", 0, "SetAutoDimOptions 0 0 0 0")
retval = swApp.Callback ( "fworks@FWPlaybackManager", 0, "SetAutoRelOptions 0")
' MSGBOX
' Algunas de las entidades seleccionadas no se pueden eliminar.

Part.WindowRedraw
Part.ViewDisplayShaded
boolstatus = Part.ForceRebuild3(True)
'FeatureWorks Block ForceRebuild
#IF FWORKS_ENABLE_SWAPI_CALLS THEN
#END IF
'FeatureWorks Block ForceRebuild
Part.ViewDisplayShaded
Part.WindowRedraw
Part.ViewDisplayShaded
'FeatureWorks Block Commenting From This Line
#IF FWORKS_ENABLE_SWAPI_CALLS THEN
Part.ViewDisplayShaded
Part.WindowRedraw
Part.ViewDisplayShaded
boolstatus = Part.EditRebuild3()
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Plano1", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Croquis29", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureRevolveCut(6.2831853071796004, True, 0, 0, 0, True, True)
Part.ClearSelection2 True
Part.WindowRedraw
Part.ViewDisplayShaded
Part.ViewDisplayShaded
boolstatus = Part.Extension.SelectByID2("", "FACE", -1.9434067056067761e-005, 0.027344966695764583, 7.2262591121077548, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis30", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis30", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.0092269927034749344, 0.013704639621003878, 7.2262591121077548, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis31", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis31", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.017195869618873871, 0.0001660084962225028, 7.2262591121078117, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis32", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis32", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.034556281789818399, 0.013293633496942903, 7.2262591121077548, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis33", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis33", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.040667237224482733, -0.0020474897722948526, 7.2262591121078117, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis34", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis34", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.037055219969758468, -0.0085937371437481147, 7.2262591121077548, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis35", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis35", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.03326976119160463, -0.0020000434360767372, 7.2262591121078117, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis36", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis36", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.039403032926017545, 0.0044599325178111826, 7.2262591121078117, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis37", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis37", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.032005556893125231, 0.0045073788540292981, 7.2262591121078117, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis38", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis38", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.031984617894650569, -0.012080973225721436, 7.2252591121078922, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis39", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis39", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.024795107863027965, -0.019437562005236941, 7.225259112107949, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis40", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis40", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.013612173051981813, -0.026078702049119329, 7.2252591121078922, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis41", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis41", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.018354104646363112, -0.040989699838384297, 7.225259112107949, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis42", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis42", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.014358152836535965, -0.034485972371804507, 7.2252591121078922, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis43", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis43", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.014561064776927424, -0.030218557353158815, 7.225259112107949, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis44", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis44", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.012017920971530316, -0.038797138903134964, 7.2252591121078922, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis45", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis45", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.0044027977897087567, -0.03867573722773443, 7.225259112107949, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis46", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis46", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.023237667368164239, -0.036647784466154576, 7.2262591121077548, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis47", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis47", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.028687486239377336, 0.035405961095413829, 7.2252591121078922, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis48", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis48", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.015775582415031408, 0.031467620845127442, 7.2252591121078922, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis49", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis49", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.023402913774916101, 0.03269823487045187, 7.2252591121078922, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis50", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis50", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.019399807847833017, 0.026273389174399142, 7.225259112107949, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis51", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis51", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.021928216444763393, 0.039288233754604107, 7.2252591121078922, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis52", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis52", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.015621503186892483, 0.032608268629381598, 7.225259112107949, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis53", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis53", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.011997277754090874, 0.037802500300109898, 7.2252591121078922, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis54", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis54", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.0071332643789645545, 0.039193341082174982, 7.225259112107949, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis55", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis55", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.00949557262106282, 0.04344898503683936, 7.2262591121077548, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis56", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis56", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.043225303289773365, 0.0023580244170489095, 7.225259112107949, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.BlankRefGeom
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis57", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Croquis57", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Set myFeature = Part.FeatureManager.FeatureCut3(True, False, False, 1, 0, 0, 0, False, False, False, False, 0, 0, False, False, False, False, False, True, True, True, True, False, 0, 0, False)
Part.ClearSelection2 True
#END IF
'FeatureWorks Block Commenting Up To This Line
boolstatus = Part.ForceRebuild3(True)
boolstatus = Part.Extension.SelectByID2("Cortar-Revolución1", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.011291922403643184, 0.0053612021441225011, 7.2198783025958164, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.00040102864312530073, 0.030062000769000008, 7.225259112107949, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Sólido importado7", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
boolstatus = Part.Extension.SelectByID2("Cortar-Revolución1", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.043079849991065539, -0.041762740867284265, 7.1588558315089008, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.020092102832245523, -0.056535894826026833, 7.1620048379690138, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Cortar-Revolución1", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
longstatus = Part.SaveAs3("C:\Users\PC\Documents\cup_holder_fer.SLDPRT", 0, 2)
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Part.ClearSelection2 True
swApp.ExitApp
End Sub
